<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MenuRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends EntityRepository
{
    public function getCurrentMenu($menuType)
    {
        $query = $this->getEntityManager()
        ->createQuery('
            SELECT m,c,p
            FROM AppBundle:Menu m 
            JOIN m.categorie c
            JOIN m.plats p
            WHERE c.nom = :nom AND m.active = :active 
            ORDER BY m.date DESC')
        ->setParameter('nom', $menuType)
        ->setParameter('active', 'oui');

        $results = $query->getOneOrNullResult();

        return $results;
    }
}
