<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BlogRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends EntityRepository
{
    public function getBlogAccueil()
    {
        $query = $this->getEntityManager()
        ->createQuery('SELECT u FROM AppBundle:Blog u ORDER BY u.date DESC')
        ->setMaxResults(3);

        $results = $query->getResult();

        return $results;
    }
}
