<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CaddieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaddieRepository extends EntityRepository
{

	public function getTotalPrix() 
	{
		// Récupere tous les objets produits de l'utilisateur
		$results = $this->getEntityManager()
		->createQuery('SELECT c FROM AppBundle:Caddie c WHERE c.identifiant = :identifiant')
		->setParameter('identifiant', session_id())
		->getResult();

		// Additionne les prix de chaque produits avec leur quantité
		$prixtotal = 0;	
		foreach($results as $result)
		{
			$prixtotal += ($result->getPrix())*($result->getQuantite());
		}

		return $prixtotal;
	}

	public function getProductCaddie($id, $productType, $user) 
	{
		$identifiant = ($user) ? 'user' : 'identifiant';
		$identifiantvalue = ($user) ? $user : session_id();

		// Récupere tous les objets produits du type demandé (menu,upsell etc)
		$query = $this->getEntityManager()
		->createQuery('SELECT c FROM AppBundle:Caddie c WHERE c.' . $identifiant . ' = :identifiant AND c.' . $productType . ' = :' . $productType .'')
		->setParameter('identifiant', $identifiantvalue)
		->setParameter($productType, $id);

		$results = $query->getResult();

		return $results;
	}


}