<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpFoundation\Session\Session;

/**
 * CommandesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandesRepository extends EntityRepository
{
	public function getCommandes()
	{
		$session = new Session;
		$commandes = $this->getEntityManager()
		->createQuery('SELECT c From AppBundle:Caddie c WHERE c.identifiant = :identifiant')
		->setParameter('identifiant', $session->getId())
		->getResult();

		return $commandes;
	}
}
