<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlatRepository extends EntityRepository
{
		public function getPlatAdmin()
	{

		$query = $this->getEntityManager()
		->createQuery('SELECT u FROM AppBundle:Plat u ORDER BY u.titre DESC');

		$results = $query->getResult();
		
		return $results;
	}
}
