<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UpsellRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UpsellRepository extends EntityRepository
{
    public function getCurrentUpsell()
    {
        $results = $this->getEntityManager()
        ->createQuery('SELECT u FROM AppBundle:Upsell u WHERE u.actif = :actif')
        ->setParameter('actif', 'oui')
        ->getResult();

        $upsells = array();
        foreach ($results as $upsell) {
            $upsells[$upsell->getCategorie()->getNom()] = $upsell;
        }

        krsort($upsells);

        return $upsells;
    }
}
